# -----------------------
# Setup Variables
# -----------------------
@unique = myModel
@deviceGroup = {{unique}}DeviceGroup
@device = {{unique}}DeviceId
@symmetricKey = 3aJ5MwKxtOjfGSgsZ8NnMa2G3wySnVnW


# -----------------------
# Get OAuth 2 Token
###
# @name login
@authUrl = login.microsoftonline.com/{{TENANT_ID}}
@resource = https%3A%2F%2Fazure-devices-provisioning.net%2F

POST https://{{authUrl}}/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&resource={{resource}}

@authToken = {{login.response.body.access_token}}



# -----------------------
# API: deviceRecords
###
# @name createDR
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "deviceId": "{{device}}",
  "status": "enabled",
  "authenticationMechanisms": [
    {
      "deviceAuthenticationType": "SymmetricKeyDeviceAuthenticationMechanism",
      "symmetricKey": "{{symmetricKey}}"
    }
  ]
}



# -----------------------
# API: deviceRecords
###
# @name queryDR
POST https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/query?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "queryType": "QueryAll"
}



# -----------------------
# API: deviceRecords
###
# @name getDR
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@etag = {{getDR.response.body.eTag}}





# ----------------------------------------------------------------------------------------------------------------------
#      ** caution only delete when fully done  **
# ----------------------------------------------------------------------------------------------------------------------
# -----------------------
# API: deviceRecords
###
# @name getDR
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{etag}}
