# -----------------------
# Setup Variables
# -----------------------
@unique = myModel
@certificateAuthority = {{unique}}CertAuthority
@provisionSettings = {{unique}}ProvisioningSettings
@deviceGroup = {{unique}}DeviceGroup
@groupRecord = {{unique}}GroupRecord


# -----------------------
# Authentication
# -----------------------

@authUrl = login.microsoftonline.com/{{TENANT_ID}}
@resource = https%3A%2F%2Fazure-devices-provisioning.net%2F

###
# @name login
POST https://{{authUrl}}/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&resource={{resource}}

@authToken = {{login.response.body.access_token}}


# -----------------------
# Group Record
# -----------------------

###
# @name http
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/groupRecords/{{groupRecord}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "{{groupRecord}}",
  "isEdge": false,
  "status": "enabled",
  "authenticationMechanisms": [
    {
      "groupAuthenticationType": "X509CAReferenceGroupAuthenticationMechanism",
      "certificateAuthorityName": "{{certificateAuthority}}"
    }
  ]
}

###
# @name http
POST https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/groupRecords/query?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "queryType": "QueryAll"
}


###
# @name http
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/groupRecords/{{groupRecord}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@etag = {{http.response.body.eTag}}


###
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/groupRecords/{{groupRecord}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{etag}}
