# Use Case 4 -- Provision Device using DPS CA and Symmetric Key Attestation

@unique = uc4
@certificateAuthority = {{unique}}CertificateAuthority
@provisionSettings = {{unique}}ProvisionSettings
@deviceGroup = {{unique}}DeviceGroup
@groupRecord = {{unique}}GroupRecord
@device = {{unique}}Device
@key = {{PRIMARY_KEY}}



# -----------------------
# Get OAuth 2 Token
###
# @name login
@resource = https%3A%2F%2Fazure-devices-provisioning.net%2F

POST https://login.microsoftonline.com/{{TENANT_ID}}/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&resource={{resource}}

@authToken = {{login.response.body.access_token}}



# -----------------------
# API: certificateAuthorities
###
# @name createCA
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/certificateAuthorities/{{certificateAuthority}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name:": "{{certificateAuthority}}",
  "certificateAuthorityType": "PrivatePreviewManagedCertificateAuthority"
}

@ca-etag = {{createCA.response.body.eTag}}



# -----------------------
# API: provisionSettings
###
# @name createPS
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/provisioningSettings/{{provisionSettings}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "{{provisionSettings}}",
  "initialTwin": {
    "tags": {
      "clean": true
    },
    "properties": {
      "desired": {}
    }
  },
  "certificateIssuancePolicy": {
    "certificateAuthorityName": "{{certificateAuthority}}",
    "validityPeriod": "P1D"
  },
  "reprovisioningSettings": {
    "updateHubAssignment": true,
    "migrateDeviceData": false
  },
  "assignmentMethod": {
    "assignmentType": "HashedAssignmentMethod",
    "targetHubs": [
      "{{HUB_HOST}}.azure-devices.net"
    ]
  }
}



# -----------------------
# API: deviceGroups
###
# @name createDG
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "{{deviceGroup}}",
  "provisioningSettingsName": "{{provisionSettings}}",
}

@dr-etag = {{createDG.response.body.eTag}}



# -----------------------
# API: deviceRecords
###
# @name createDR
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "deviceId": "{{device}}",
  "status": "enabled",
  "authenticationMechanisms": [
    {
      "deviceAuthenticationType": "SymmetricKeyDeviceAuthenticationMechanism",
      "symmetricKey": "{{PRIMARY_KEY}}"
    }
  ]
}

@dr-etag = {{createDR.response.body.eTag}}



# -----------------------
# Generate deviceToken
###
# @name deviceToken
POST https://{{FUNCTIONS-JS}}.azurewebsites.net/api/DeviceToken

{
  "registrationId": "{{device}}",
  "idScope": "{{ID_SCOPE}}",
  "symmetricKey": "{{PRIMARY_KEY}}"
}

@deviceSAS = {{deviceToken.response.body.outputs.sasToken}}



# -----------------------
# Generate csr
###
# @name csrGenerator
POST https://{{FUNCTIONS-CORE}}.azurewebsites.net/api/CSRGenerator

{
  "subjectName": "{{device}}"
}

@deviceCSR = {{csrGenerator.response.body.outputs.csr}}


# -----------------------
# API: register
###
# @name register
PUT https://global.azure-devices-provisioning.net/{{ID_SCOPE}}/registrations/{{device}}/register?api-version=2019-05-01
Authorization: {{deviceSAS}}
Content-Type: application/json

{
  "registrationId": "{{device}}",
  "csr": "{{deviceCSR}}",
  "payload": {}
}



# -----------------------
# API: certificateAuthorities
###
# @name getCA
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/certificateAuthorities/{{certificateAuthority}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@etag = {{getCA.response.body.eTag}}



# -----------------------
# API: provisionSettings
###
# @name getPS
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/provisioningSettings/{{provisionSettings}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@ps-etag = {{getPS.response.body.eTag}}



# -----------------------
# API: deviceGroups
###
# @name getDG
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@dg-etag = {{getDG.response.body.eTag}}



# -----------------------
# API: deviceRecords
###
# @name getDR
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@dr-etag = {{getDR.response.body.eTag}}





# ----------------------------------------------------------------------------------------------------------------------
#      ** caution only delete when fully done  **
# ----------------------------------------------------------------------------------------------------------------------

### DELETE DeviceRecord
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{dr-etag}}

### DELETE DeviceGroup
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{dg-etag}}

### DELETE ProvisionSettings
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/provisioningSettings/{{provisionSettings}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{ps-etag}}

# -----------------------
# API: certificateAuthorities
###
# @name deleteCA
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/certificateAuthorities/{{certificateAuthority}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{etag}}
