# Use Case 7 -- Provision Devices in Bulk using Symmetric Key and new Object Model

# -----------------------
# Setup Variables
# -----------------------
@unique = uc7
@provisionSettings = {{unique}}ProvisionSettings
@deviceGroup = {{unique}}DeviceGroup
@groupRecord = {{unique}}GroupRecord
@device1 = {{unique}}Device1
@device2 = {{unique}}Device2
@masterKey = 3aJ5MwKxtOjfGSgsZ8NnMa2G3wySnVnW
@derivedKey1 = 4HRdv5tR38GC+jxlkdHGkStjaYpSoJt9OD9zOKIPu6I=
@derivedKey2 = ZE92Bv06mh5OysTi0+jBr25oW7gj3jnDnoSVorZ92dY=



# -----------------------
# Get OAuth 2 Token
###
# @name login
@resource = https%3A%2F%2Fazure-devices-provisioning.net%2F

POST https://login.microsoftonline.com/{{TENANT_ID}}/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&resource={{resource}}

@authToken = {{login.response.body.access_token}}


# -----------------------------------------------------------------------------------------------------------------------
# -----------------------
# Create Object Model
# -----------------------


###  CREATE ProvisionSettings
# @name ps
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/provisioningSettings/{{provisionSettings}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "{{provisionSettings}}",
  "initialTwin": {
    "tags": {
      "clean": true
    },
    "properties": {
      "desired": {}
    }
  },
  "reprovisioningSettings": {
    "updateHubAssignment": true,
    "migrateDeviceData": false
  },
  "assignmentMethod": {
    "assignmentType": "HashedAssignmentMethod",
    "targetHubs": [
      "{{HUB_HOST}}.azure-devices.net"
    ]
  }
}

@ps-etag = {{ps.response.body.eTag}}


###  CREATE DeviceGroup
# @name dg
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "{{deviceGroup}}",
  "provisioningSettingsName": "{{provisionSettings}}",
}

@dg-etag = {{dg.response.body.eTag}}


###  CREATE GroupRecord
# @name gr
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/groupRecords/{{groupRecord}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "{{groupRecord}}",
  "isEdge": false,
  "status": "enabled",
  "authenticationMechanisms": [
    {
      "groupAuthenticationType": "SymmetricKeyGroupAuthenticationMechanism",
      "symmetricKey": "{{masterKey}}"
    }
  ]
}

@gr-etag = {{gr.response.body.eTag}}


###  CREATE DeviceRecord  ** NOTE:  DeviceRecords are created automatically at time of Provisioning.
# @name dr1
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device1}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "deviceId": "{{device1}}",
  "status": "enabled",
  "authenticationMechanisms": [
    {
      "deviceAuthenticationType": "SymmetricKeyDeviceAuthenticationMechanism",
      "symmetricKey": "{{derivedKey1}}"
    }
  ]
}

@dr1-etag = {{dr1.response.body.eTag}}


###  CREATE DeviceRecord  ** NOTE:  DeviceRecords are created automatically at time of Provisioning.
# @name dr2
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device2}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "deviceId": "{{device2}}",
  "status": "enabled",
  "authenticationMechanisms": [
    {
      "deviceAuthenticationType": "SymmetricKeyDeviceAuthenticationMechanism",
      "symmetricKey": "{{derivedKey2}}"
    }
  ]
}

@dr2-etag = {{dr2.response.body.eTag}}


# -----------------------------------------------------------------------------------------------------------------------
# -----------------------
# Get Object Model
# -----------------------


###  GET ProvisionSettings
# @name ps
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/provisioningSettings/{{provisionSettings}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@ps-etag = {{ps.response.body.eTag}}


###  GET DeviceGroup
# @name dg
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@dg-etag = {{dg.response.body.eTag}}


### List GroupRecords
POST https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/groupRecords/query?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "queryType": "QueryAll"
}


###  GET GroupRecord
# @name gr
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/groupRecords/{{groupRecord}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@gr-etag = {{gr.response.body.eTag}}


### LIST DeviceRecords
POST https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/query?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "queryType": "QueryAll"
}


### GET DeviceRecord
# @name dr1
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device1}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@dr1-etag = {{dr1.response.body.eTag}}


### GET DeviceRecord
# @name dr2
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device2}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@dr2-etag = {{dr2.response.body.eTag}}


# -----------------------------------------------------------------------------------------------------------------------
# -----------------------
# Delete Object Model
# -----------------------

### DELETE DeviceRecord
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device1}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{dr1-etag}}

### DELETE DeviceRecord
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device2}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{dr2-etag}}

### DELETE DeviceGroup
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{dg-etag}}

### DELETE GroupRecord
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/groupRecords/{{groupRecord}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{gr-etag}}

### DELETE ProvisionSettings
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/provisioningSettings/{{provisionSettings}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{ps-etag}}
