# Use Case 3 - Provision Device Using TPM

# -----------------------
# Setup Variables
# -----------------------
@unique = uc3
@provisionSettings = {{unique}}ProvisionSettings
@deviceGroup = {{unique}}DeviceGroup
@groupRecord = {{unique}}GroupRecord
@device = {{unique}}Device
@tpmPublic = AToAAQALAAMAsgAgg3GXZ0SEs/gakMyNRqXXJP1S124GUgtk8qHaGzMUaaoABgCAAEMAEAgAAAAAAAEA5DZrM0/0VxccrFqzhSg21VfG2mMR5OqHH70G67ZU5AiTk9eZWGWrYX+AAf7zclhPAFFG+L2HHD0rQWb1GJxrjDB7GM2mk2JvxaoYVe5e942ZyAQCwl959J989mY7FmoXtEjN8H7SECO6xrEPgfCMnXl8zens0Eo3/xpZT9dXVtaGhQu3RRDM4DwRWV8rDvfRB4Y/0dk8B/YQwe0mElAOpSU4EqZe+q27Julvnd9isg2VzZRfs10BlrgKWp1J7yyY+5NE5oB9Mzr+1pn6Vbtdg1d9BpUlfNMD1cKz3azsqSW8BFtX2zUJklfWFX+SFxsPB/mxw9pbLHfn8fJ+zm1TsQ==


# -----------------------------------------------------------------------------------------------------------------------
# -----------------------
# Authentication
# -----------------------

@authUrl = login.microsoftonline.com/{{TENANT_ID}}
@resource = https%3A%2F%2Fazure-devices-provisioning.net%2F

###  OAUTH 2.0 Login
# @name login
POST https://{{authUrl}}/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&resource={{resource}}

@authToken = {{login.response.body.access_token}}


# -----------------------------------------------------------------------------------------------------------------------
# -----------------------
# Create Object Model
# -----------------------


###  CREATE ProvisionSettings
# @name ps
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/provisioningSettings/{{provisionSettings}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "{{provisionSettings}}",
  "initialTwin": {
    "tags": {
      "clean": true
    },
    "properties": {
      "desired": {}
    }
  },
  "reprovisioningSettings": {
    "updateHubAssignment": true,
    "migrateDeviceData": false
  },
  "assignmentMethod": {
    "assignmentType": "HashedAssignmentMethod",
    "targetHubs": [
      "{{HUB_HOST}}.azure-devices.net"
    ]
  }
}

@ps-etag = {{ps.response.body.eTag}}


###  CREATE DeviceGroup
# @name dg
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "{{deviceGroup}}",
  "provisioningSettingsName": "{{provisionSettings}}",
}

@dg-etag = {{dg.response.body.eTag}}


###  CREATE DeviceRecord
# @name dr
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "deviceId": "{{device}}",
  "status": "enabled",
  "authenticationMechanisms": [
    {
      "deviceAuthenticationType": "TpmDeviceAuthenticationMechanism",
      "endorsementKey": "{{tpmPublic}}"
    }
  ],
  "deviceGroupName": "{{deviceGroup}}"
}

@dr-etag = {{dr.response.body.eTag}}



# -----------------------------------------------------------------------------------------------------------------------
# -----------------------
# Get Object Model
# -----------------------


###  GET ProvisionSettings
# @name ps
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/provisioningSettings/{{provisionSettings}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@ps-etag = {{ps.response.body.eTag}}


###  GET DeviceGroup
# @name dg
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@dg-etag = {{dg.response.body.eTag}}


### GET DeviceRecord
# @name dr
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

@dr-etag = {{dr.response.body.eTag}}


# -----------------------------------------------------------------------------------------------------------------------
# -----------------------
# Delete Object Model
# -----------------------

### DELETE DeviceRecord
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/deviceRecords/{{device}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{dr-etag}}

### DELETE DeviceGroup
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{dg-etag}}

### DELETE GroupRecord
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/deviceGroups/{{deviceGroup}}/groupRecords/{{groupRecord}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{gr-etag}}

### DELETE ProvisionSettings
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/provisioningSettings/{{provisionSettings}}?api-version=2019-05-01
Authorization: Bearer {{authToken}}
Content-Type: application/json
If-Match: {{ps-etag}}
