

@DPS_HOST = dpswithcertmgmt
@IOT_HUB = hubwithcertmgmt
@id = test2


# -----------------------
# Enrollment Groups
# -----------------------

###
# @name enrollmentGroup
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollmentGroups/{{id}}?api-version=2019-03-31
Authorization: {{DPS_TOKEN}}
Content-Type: application/json

{
  "enrollmentGroupId": "{{id}}",
  "allocationPolicy": "hashed",
  "attestation": {
    "type": "symmetricKey"
  },
  "capabilities": {
    "iotEdge": false
  },
  "provisioningStatus": "enabled",
  "reprovisionPolicy": {
    "updateHubAssignment": true,
    "migrateDeviceData": true
  },
  "iotHubs": [
    "{{IOT_HUB}}.azure-devices.net"
  ]
}

###
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollmentGroups/{{id}}?api-version=2019-03-31
Authorization: {{DPS_TOKEN}}
Content-Type: application/json

###
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollmentGroups/{{id}}?api-version=2019-03-31
Authorization: {{DPS_TOKEN}}
Content-Type: application/json



# -----------------------
# Individual Enrollment
# -----------------------

###
# @name enrollment
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollments/{{id}}?api-version=2019-03-31
Authorization: {{DPS_TOKEN}}
Content-Type: application/json

{
  "registrationId": "{{id}}",
  "registrationState": {
    "registrationId": "{{id}}",
    "status": "unassigned"
  },
  "attestation": {
    "type": "symmetricKey"
  },
  "capabilities": {
    "iotEdge": false
  },
  "provisioningStatus": "enabled",
  "reprovisionPolicy": {
    "updateHubAssignment": true,
    "migrateDeviceData": true
  },
  "allocationPolicy": "hashed",
  "iotHubs": [
    "{{IOT_HUB}}.azure-devices.net"
  ]
}

###
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollments/{{id}}?api-version=2019-03-31
Authorization: {{DPS_TOKEN}}
Content-Type: application/json


###
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollments/{{id}}?api-version=2019-03-31
Authorization: {{DPS_TOKEN}}
Content-Type: application/json
