# Use Case 1 -- Individual Enrollement using Symmetric Key

@unique = uc1
@device = {{unique}}Device


# -----------------------
# Get DPS Access Token
###
# @name dpsToken
POST https://dpsprivatepreview.azurewebsites.net/api/ServiceToken

{
  "connectionString": "{{DPS_CONNECTIONSTRING}}"
}

@serviceSAS = {{dpsToken.response.body.outputs.sasToken}}



# -----------------------
# Individual Enrollment
###
# @name createEnrollment
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollments/{{device}}?api-version=2019-03-31
Authorization: {{serviceSAS}}
Content-Type: application/json

{
  "registrationId": "{{device}}",
  "registrationState": {
    "registrationId": "{{device}}",
    "status": "unassigned"
  },
  "attestation": {
    "type": "symmetricKey",
    "symmetricKey": {
      "primaryKey": "{{PRIMARY_KEY}}",
      "secondaryKey": "{{SECONDARY_KEY}}"
    }
  },
  "capabilities": {
    "iotEdge": false
  },
  "provisioningStatus": "enabled",
  "reprovisionPolicy": {
    "updateHubAssignment": true,
    "migrateDeviceData": true
  },
  "allocationPolicy": "hashed",
  "iotHubs": [
    "{{HUB_HOST}}.azure-devices.net"
  ]
}


# -----------------------
# Individual Enrollment
###
# @name getEnrollment
GET https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollments/{{device}}?api-version=2019-03-31
Authorization: {{serviceSAS}}



# -----------------------
# AttestationMechanism
###
# @name getAttestation
POST https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollments/{{device}}/attestationmechanism?api-version=2019-03-31
Authorization: {{serviceSAS}}

@accessKey = {{getAttestation.response.body.symmetricKey.primaryKey}}



# -----------------------
# Get Device Access Token
###
# @name deviceToken
POST https://dpsprivatepreview.azurewebsites.net/api/DeviceToken

{
  "registrationId": "{{device}}",
  "idScope": "{{ID_SCOPE}}",
  "symmetricKey": "{{accessKey}}"
}

@deviceSAS = {{deviceToken.response.body.outputs.sasToken}}



# -----------------------
# Device Register
###
# @name register
PUT https://global.azure-devices-provisioning.net/{{ID_SCOPE}}/registrations/{{device}}/register?api-version=2019-03-31
Authorization: {{deviceSAS}}
Content-Type: application/json

{
  "registrationId": "{{device}}",
  "payload": {}
}


# ----------------------------------------------------------------------------------------------------------------------
#      ** caution only delete when fully done due to caching time constraints **
# ----------------------------------------------------------------------------------------------------------------------
# Individual Enrollment
###
# @name deleteEnrollment
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollments/{{device}}?api-version=2019-03-31
Authorization: {{serviceSAS}}
Content-Type: application/json
