# Use Case 2 -- Group Enrollment using Symmetric Keys and Derived Keys

@unique = uc2
@deviceGroup = {{unique}}DeviceGroup
@device = {{unique}}Device


# -----------------------
# Get DPS Access Token
###
# @name dpsToken
POST https://{{FUNCTIONS-JS}}.azurewebsites.net/api/ServiceToken

{
  "connectionString": "{{DPS_CONNECTIONSTRING}}"
}

@serviceSAS = {{dpsToken.response.body.outputs.sasToken}}



# -----------------------
# Group Enrollment
###
# @name createEnrollment
PUT https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollmentGroups/{{deviceGroup}}?api-version=2019-03-31
Authorization: {{serviceSAS}}
Content-Type: application/json

{
  "enrollmentGroupId": "{{deviceGroup}}",
  "allocationPolicy": "hashed",
  "attestation": {
    "type": "symmetricKey",
    "symmetricKey": {
      "primaryKey": "{{PRIMARY_KEY}}",
      "secondaryKey": "{{SECONDARY_KEY}}"
    }
  },
  "capabilities": {
    "iotEdge": false
  },
  "provisioningStatus": "enabled",
  "reprovisionPolicy": {
    "updateHubAssignment": true,
    "migrateDeviceData": true
  },
  "iotHubs": [
    "{{HUB_HOST}}.azure-devices.net"
  ]
}

@accessKey = {{createEnrollment.response.body.attestation.symmetricKey.primaryKey}}


# -----------------------
# Individual Enrollment
###
# @name getEnrollment

GET https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollmentGroups/{{deviceGroup}}?api-version=2019-03-31
Authorization: {{serviceSAS}}



# -----------------------
# AttestationMechanism
###
# @name getAttestation
POST https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollmentGroups/{{deviceGroup}}/attestationmechanism?api-version=2019-03-31
Authorization: {{serviceSAS}}

@accessKey = {{getAttestation.response.body.symmetricKey.primaryKey}}


# -----------------------
# Get Device Derived Key
###
# @name derivedKey
POST https://{{FUNCTIONS-JS}}.azurewebsites.net/api/DerivedKey

{
  "registrationId": "{{device}}",
  "symmetricKey": "{{accessKey}}"
}

@deviceKey = {{derivedKey.response.body.outputs.derivedKey}}


# -----------------------
# Get Device Access Token
###
# @name deviceToken
POST https://{{FUNCTIONS-JS}}.azurewebsites.net/api/DeviceToken

{
  "registrationId": "{{device}}",
  "idScope": "{{ID_SCOPE}}",
  "symmetricKey": "{{deviceKey}}"
}

@deviceSAS = {{deviceToken.response.body.outputs.sasToken}}



# -----------------------
# API: register
###
# @name register
PUT https://global.azure-devices-provisioning.net/{{ID_SCOPE}}/registrations/{{device}}/register?api-version=2019-03-31
Authorization: {{deviceSAS}}
Content-Type: application/json

{
  "registrationId": "{{device}}",
  "payload": {}
}



# ----------------------------------------------------------------------------------------------------------------------
#      ** caution only delete when fully done due to caching time constraints **
# ----------------------------------------------------------------------------------------------------------------------
# Group Enrollment
###
# @name deleteEnrollment
DELETE https://{{DPS_HOST}}.azure-devices-provisioning.net/enrollmentGroups/{{deviceGroup}}?api-version=2019-03-31
Authorization: {{serviceSAS}}
Content-Type: application/json
